In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as mlp

In [135]:
x1 = np.array([[1,2,3,4],[2,3,4,5]])
x2 = np.array([[5,6,7,8],[5,6,7,9],[5,6,7,8],[1,2,5,6]])
y2 = np.array([1,2,3,1])

In [136]:
result = np.abs(x1[:, np.newaxis] - x2)
distance = np.sum(result**2, axis = 2)**0.5

In [147]:
distance

array([[8.        , 8.54400375, 8.        , 2.82842712],
       [6.        , 6.55743852, 6.        , 2.        ]])

In [144]:
k=2

In [138]:
sorted_indices = np.argsort(distance, axis=1)

In [139]:
sorted_indices


array([[3, 0, 2, 1],
       [3, 0, 2, 1]])

In [141]:
label_array = y2[sorted_indices]

In [168]:
label_array

array([[1, 1, 3, 2],
       [1, 1, 3, 2]])

In [222]:
classes, counts = np.unique(label_array, return_counts=True, axis = 1)
classes


array([[1, 2, 3],
       [1, 2, 3]])

In [223]:
counts

array([2, 1, 1])

In [233]:
array = np.array([[1, 1, 3, 2, 3],
       [1, 3, 3, 2, 3]])
classes, counts = np.unique(array, return_counts=True, axis = 1)
classes

array([[1, 1, 2, 3],
       [1, 3, 2, 3]])

In [209]:
counts

array([1, 1, 1, 1])

In [244]:
data = np.array([[1, 2, 2, 2, 1, 1],
                 [1, 2, 2, 3, 2, 1]])

# Find the majority value in each row
majority_values = np.apply_along_axis(lambda row: np.bincount(row).argmax(), axis=1, arr=data)

print(majority_values)

[1 2]
